# Generated by Django 3.2.13 on 2022-05-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/jqueryenjoyer/image/upload/v1652191894/APIS/default_profile_txlx6h.jpg', upload_to='images/'),
        ),
    ]
