# Generated by Django 3.2.13 on 2022-05-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
